api:
  url: http://localhost:8080/api/v1
datasource:
  url: jdbc:postgresql://ec2-18-204-101-137.compute-1.amazonaws.com:5432/d2dskh6gqc29mq
  username: qescamtxhtiqqq
  password: 04798a3b2ecee642ccfefcb8983e427e0caf377dee0f2fdf23759a6b56323077
webhook:
  url: https://localhost:44360/sei/webhook