base:
  url: https://227e-136-52-65-147.ngrok.io/api/v1
webhook:
  url: https://localhost:44360/sei/webhook
sei:
  url: https://scorpion.caveon.com/api/exams/{exam_id}/deliveries/{delivery_id}
auth:
  header: M2RmMjRhNTItMGUzYy00NjllLWIyZjAtMTliY2ExNGZmNGUzOmRjNmVkYmJjOWJjNDU2NGFhNjg2ZGRhNDFlMGEwMDE4
datasource:
  url: jdbc:postgresql://ec2-18-204-101-137.compute-1.amazonaws.com:5432/d2dskh6gqc29mq
  username: qescamtxhtiqqq
  password: 04798a3b2ecee642ccfefcb8983e427e0caf377dee0f2fdf23759a6b56323077
