base:
  url: https://7a2e-136-52-65-147.ngrok.io/api/v1
webhook:
  url: https://okta-certification.ngrok.io/v2/sei/webhook
sei:
  url: https://scorpion.caveon.com/api/set_response/{response_id}?external_token={external_token}
auth:
  header: MDk0ZGQ0NTMtN2I2ZS00MGQ0LTg3MDItYjIxNGJjYWYyZGYzOmQzNTkwNjQwZmEwNTA3MzU3MTAyMzY2M2Q0ZTFiMmZl
datasource:
  url: jdbc:postgresql://ec2-34-196-62-252.compute-1.amazonaws.com:5432/d7e6ki30a9ohng
  username: uc5dsbqnc9pmt5
  password: p85db4b6c392ad1a80564c54a7d4353f82b1d799cf59fa76b991b9a75da09200c
#datasource:
#  url: jdbc:postgresql://ec2-18-204-101-137.compute-1.amazonaws.com:5432/d2dskh6gqc29mq
#  username: qescamtxhtiqqq
#  password: 04798a3b2ecee642ccfefcb8983e427e0caf377dee0f2fdf23759a6b56323077